version: '3'
services:
  db:
    image: mysql
    volumes:
      - "./data/db:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: smsdb
      MYSQL_USER: sms
      MYSQL_PASSWORD: passer
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: always
    networks:
      - sms-network

  www:
    depends_on:
      - db
    image: php:8.0-apache
    volumes:
      - ./data/www:/var/www/html
    ports:
      - 8080:80
      - 443:443
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - sms-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: sms
      MYSQL_PASSWORD: passer
      MYSQL_DATABASE: smsdb
    restart: always
    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge